image: gcc

# build the project
build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cmake -B Build
    - cmake --build Build
  artifacts:
    paths:
      - Build/IOTest
      - Build/algorithmTest
      - Build/main

# run tests using the binary built before
test:
  stage: test
  script:
    - cd Build
    - ./IOTest 
    - ./algorithmTest
  artifacts:
    paths:
      - Output/test.out

# test run demo
demo:
  stage: test
  script:
    - cd Build
    - ./main "../Input/test_mat.in" "../Input/test_e.in" "../Output/demo.out" e xx
  artifacts:
    paths:
      - Output/demo.out


# test run visualization.py
visualization:
  stage: test
  image: python:latest
  before_script: 
    - pip install plotly==5.13.1
    - pip install kaleido
    - pip install packaging
  script: 
    - cd Src
    - python visualization.py "../Output/test_vis.out" "../Output/test_vis_noopt.png"
    - python visualization.py "../Output/test_vis.out" "../Output/test_vis_slicex.png" -slice x 0 1 2 0.7
    - python visualization.py "../Output/test_vis.out" "../Output/test_vis_slicey.png" -slice y 0 1 2 0.7
    - python visualization.py "../Output/test_vis.out" "../Output/test_vis_slicez.png" -slice z 0 1.5 3 0.7
  artifacts:
    paths:
      - Output/test_vis_noopt.png
      - Output/test_slicex.png
      - Output/test_slicey.png
      - Output/test_slicez.png

