image: gcc

# build the project
build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cmake -B Build
    - cmake --build Build
  artifacts:
    paths:
      - Build/IOTest

# run tests using the binary built before
test:
  stage: test
  script:
    - cd Build
    - ./IOTest 

# test run visualization.py
visualization:
  stage: test
  image: python:latest
  before_script: 
    - pip install plotly==5.13.1
    - pip install kaleido
  script: 
    - cd Build
    - python visualization.py "../Output/test.out"
