image: gcc

# build the project
build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cmake -B Build
    - cmake --build Build
    - cp -R Input Build/Input
  artifacts:
    paths:
      - Build/IOTest 
      - Build/Input

# run tests using the binary built before
test:
  stage: test
  script:
    - cd Build
    - ./IOTest # would like to do this using ctest to run all tests with a single command

# deploy:
#   stage: deploy
#   script: 
#     - ...
