image: gcc

# build the project
build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - cmake -B Build
    - cmake --build Build
  artifacts:
    paths:
      - Build/IOTest
      - Build/algorithmTest

# run tests using the binary built before
test:
  stage: test
  script:
    - cd Build
    - ./IOTest 
    - ./algorithmTest
  artifacts:
    paths:
      - Output/test.out

# test run demo
demo:
  stage: test
  script:
    - cd Build
    - ./demo "../Input/test_mat.in" "../Input/test_e.in" "../Output/demo.out" e xx
  artifacts:
    paths:
      - Output/demo.out

# test run visualization.py
visualization:
  stage: test
  image: python:latest
  before_script: 
    - pip install plotly==5.13.1
    - pip install kaleido
    - pip install packaging
  script: 
    - cd Src
    - python visualization.py "../Output/test.out" "../Output/test.png"
  artifacts:
    paths:
      - Output/test.png
